<?php require_once('header.php'); ?>
    <div class="container privacy-policy">
      <h2>Privacy Policy</h2>
      <div class="row">
        <div class="col-md-12">
          <div class="title">Privacy Statement</div>
          <div class="statement">
            This Privacy Statement informs you about the type of personal data that is collected and received through our website https://www.getmumm.com (“website”) and our cloud-based services that relate to the application mumm (“mumm”), and about how we use, share, retain and protect such personal data.
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="title">Who we are</div>
          <div class="statement">
            We are the Dutch company Bohemian B.V. (“we”, or “us”) and have our registered office at Marconistraat 20, 2562 JD, the Hague, the Netherlands: (KVK) 60360461. VAT number: NL8538.75.273.B01. We are the controller responsible for the processing of personal data through the website and mumm.
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="title">How we obtain personal data</div>
          <div class="statement">
            <p>
              We collect and receive personal data through the website and mumm. Personal data means any information relating to an identified or identifiable natural person.
            </p>
            <p>
              First of all, we collect personal data that you choose to voluntarily provide to us for your use of the website and Sketch Cloud. Also, we collect personal information throughmumm. In addition, we collect certain personal data by using cookies, including similar technologies such as local storage when you visit the website.
            </p>
            <p>

Cookies are bits of text that are placed on your computer’s hard drive or mobile device when you visit certain websites. Cookies hold information that may be accessible by the party that places the cookie, which is either the website itself (first part cookie) or a third party (third party cookies). You do have control over cookies, and can refuse the use of cookies by selecting the appropriate setting on your browser. Most browsers will tell you how to stop accepting new cookies, how to be notified when you receive a new cookie, and how to disable or delete existing cookies. Please note, however, that by not accepting or deleting the use of cookies, you may not be able to use the website and mumm.
            </p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="title">On the website, we use cookies for the following purposes:</div>
          <div class="statement">
            To gather website statistical data to analyze how our users use the website, such as which pages are visited, how long pages were visited and the paths taken by visitors to our website as they move from page to page. These cookies are placed by the domain https://getmumm.com;
To provide authentication (i.e. to keep you logged in between sessions). The information collected using local storage is stored on your browser and persists after your browser is closed.
For the purpose listed under 1), we use Google Analytics. Google Analytics is a web analytics service provided by Google, Inc., which uses cookies to help. The information generated by the cookie about your use of our website (such as your IP address, the URL visited, the date and time the page was viewed) will be transmitted and stored by Google on servers in the United States or any other country in which Google maintains facilities. Your IP address will be masked by setting the last octet of your IP address to zero before it is stored by Google. Google will use this information to monitor your use of our website, and to compile reports on website activity for us. Based on our agreement with Google, Google is not allowed to use this information for their own purposes and may only transfer this information to third parties where required by law, or where such third parties process information on Google’s behalf.
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid plates">
      <div class="plate plate1">
        <img src="assets/img/plate1.png">
      </div>
      <div class="plate plate2">
        <img src="assets/img/plate2.png">
      </div>
        <div class="plate plate3">
        <img src="assets/img/plate3.png">
      </div>
        <div class="plate plate4">
        <img src="assets/img/plate4.png">
      </div>
    <div class="container get-started text-center">
      <div class="row">
        <div class="col-md-12">
          <h5>Love to cook?</h5>
          <div>Join Mumm as a Cook Now!</div>
          <button class="btn btn-primary">GET STARTED</button>
        </div>
      </div>
    </div>
  </div>
<?php require_once('footer.php');?>
